tables:
tables:
  - name: table1
    rows: 1000
    truncate: true
  - name: table2
    rows: 5000
    truncate: false
  - name: table3
    rows: 1000
    truncate: true
  - name: table4
    rows: 5000
    truncate: false
  - name: table5
    rows: 1000
    truncate: true
  - name: table6
    rows: 5000
    truncate: false
  - name: table7
    rows: 1000
    truncate: true
  - name: table8
    rows: 5000
    truncate: false
  - name: table9
    rows: 1000
    truncate: true
  - name: table10
    rows: 5000
    truncate: false
  - name: table11
    rows: 1000
    truncate: true
  - name: table12
    rows: 5000
    truncate: false
  - name: table13
    rows: 1000
    truncate: true
  - name: table14
    rows: 20000
    truncate: false
