#database_name 이용해서 db 접근.
database:
  type: mysql
  driver: pymysql
  user: root
  password: 208300
  host: localhost
  port: 3306
  #databas_name은 아무것도 입력 없을 시 기본값, 사용자 입력이 우선됨.
  default_db: airportdb