source:
  host: localhost
  user: root
  password: your_mysql_password
  database: your_mysql_database

target:
  uri: mongodb://localhost:27017
  database: your_mongodb_database

tables:
  - mysql_table: table1
    mongo_collection: collection1
  - mysql_table: table2
    mongo_collection: collection2